### ISSUE TITLE
Упростить Programmatic Config

### ISSUE THREAD

**Issue by coursar** [Desire456/spring-course-1#1]
https://github.com/Desire456/spring-course-1/blob/b81f63247e509c201e6ad208fc522bab222e7ce5/src/test/java/ProgrammaticTest.java#L22-L38

Должно быть:
```java
        context.registerBean("dataSource", ??? <- сюда данные вроде host, port, db, user, pass);
        context.registerBean(ProgrammaticConfigPostgresConnector.class,
            ???, ??? <- сюда "ссылка" на bean, см интерфейс BeanReference
        );
```

**Comment by Desire456** [comment]
Первое невозможно, так как у `PGSimpleDataSource` нет такого конструктора, второе поправил.

**Comment by coursar** [comment]
По п.1 - зачем конструктор? У вас `registerBean` перегруженный и вы вполне можете закидывать `property`, например, вот так:

```java
    context.registerBean(PGSimpleDataSource.class, beadDefinition -> beadDefinition.getPropertyValues()
        .addPropertyValues(Map.of(
            "serverNames", "${db.serverName}",
            "databaseName", "${db.databaseName}",
            "portNumbers", "${db.port}",
            "user", "${db.username}",
            "password", "${db.password}"
        )));
```

**Comment by Desire456** [comment]
Точно. Не нашел эту возможность. Тогда сейчас поправлю)

**Comment by Desire456** [comment]
Поправил.

**Comment by coursar** [comment]
Issue надо закрывать, если сделано, желательно [сообщением коммита](https://github.blog/2013-01-22-closing-issues-via-commit-messages/), в котором и было исправление.
