### ISSUE TITLE
Double Curly Braces Anti Pattern

### ISSUE THREAD

**Issue by coursar** [Desire456/spring-course-1#5]
https://github.com/Desire456/spring-course-1/blob/b8974be961ec48bbf5ae007294fb988a7b1958e1/src/test/java/ProgrammaticTest.java#L24-L32

**Comment by Desire456** [comment]
@coursar вот попробовал, не закрылось почему-то. Fixed слово есть, issue номер есть. Подскажите пожалуйста, что не так делаю?

**Comment by coursar** [comment]
Надо в стиле: `fixed #5 ...`

**Comment by Desire456** [comment]
Понял, спасибо. Буду применять в дальнейшем
